### ISSUE TITLE
How to get the login details?

### ISSUE THREAD

**Issue by saikirannani123** [microsoftgraph/iOS-objectivec-connect-sample#10]
I just want to know how i can get the details of the account that i logged in

**Comment by JohnMAustin78** [comment]
Are you asking if you can use the Microsoft Graph API to get properties of the me resource?

**Comment by jasonjoh** [comment]
Closing this issue as we are archiving this repository. Please see https://github.com/microsoftgraph/msgraph-training-ios-objectivec for an Objective-C sample.
