### ISSUE TITLE
not able to login with my organization account

### ISSUE THREAD

**Issue by dammy1984** [microsoftgraph/iOS-objectivec-connect-sample#11]
I am able to build and run the sample, however I am not able to login. After I enter my email id, it is saying 'We're taking to organization sign-in page'. however I have never seen the login page. I suppose this is problem with redirect url

If I use the same URL in my mac machine safari browser it is working. Please do the needful

**Comment by JohnMAustin78** [comment]
Hello,

Does your organization have an Office 365 tenant? Can you verify that your redirect url looks like: 'msal<app client id Guid>://auth' ?  For example, 'msal99231e79-a109-40e0-b609-...://auth'  I truncated the client id in my example.

John

**Comment by jasonjoh** [comment]
Closing this issue as we are archiving this repository. Please see https://github.com/microsoftgraph/msgraph-training-ios-objectivec for an Objective-C sample.
