### ISSUE TITLE
 HTTP load failed (error code: -999

### ISSUE THREAD

**Issue by shobhakartiwari** [microsoftgraph/iOS-objectivec-connect-sample#12]
Implemented Graph api for iOS app . It was working fine for XCode 8.3.2 and iOS 10 but after coming into XCode 9 and iOS 11 and now its stop working .

It gives error :  HTTP load failed (error code: -999

Login Screen is not opening , Kindly guide me is there any change in the Graph SDK for iOS which i need to add into my current project . Kindly help .

**Comment by JohnMAustin78** [comment]
I haven't tested this sample against the combination of XCode 9 and iOS 11.  XCode 9 and iOS 10 are working.  I will verify your results and if the problem lies in the sample code, I will will the issue.

**Comment by defib22** [comment]
I am also facing the same issue on Xcode 11.2 and iOS 13.

**Comment by jasonjoh** [comment]
Closing this issue as we are archiving this repository. Please see https://github.com/microsoftgraph/msgraph-training-ios-objectivec for an Objective-C sample.
