### ISSUE TITLE
Apple Mach-O Linker Error

### ISSUE THREAD

**Issue by chandelr** [microsoftgraph/iOS-objectivec-connect-sample#14]
After 'pod install' I am getting below error and not building it, I am using XCode 8.3.3.
_Apple Mach-O linker error- Linker command failed with exit code 1 (use -v to see invocation)_

**Comment by jasonjoh** [comment]
Closing this issue as we are archiving this repository. Please see https://github.com/microsoftgraph/msgraph-training-ios-objectivec for an Objective-C sample.
