### ISSUE TITLE
How to Send PDF and Images in Mail attachment from Microsoft graph SDK for iOS

### ISSUE THREAD

**Issue by TaralRathod** [microsoftgraph/iOS-objectivec-connect-sample#7]
I am using Microsoft graph SDK for sending mail using office 365 account from my iOS application recently I am able to send mail body but I am not able to send attachments with it, I am referring https://graph.microsoft.io/en-us/docs/api-reference/v1.0/resources/fileattachment link for the attachment but could not able to send attachments.

I have tried to hit https://graph.microsoft.com/v1.0/me/sendMail URL using following JSON

{
"message":{
"subject":"Meet for lunch?",
"hasAttachments":true,
"body":{
"contentType":"Text",
"content":"The new cafeteria is open."
},
"toRecipients":[
{
"emailAddress":{
"address":"abc@123.onmicrosoft.com"
}
}
],
"attachments":[
{
"@odata.type":"#Microsoft.OutlookServices.FileAttachment",
"name":"menu.png",

"Content-Type":"multipart/mixed"

"contentBytes":"base64 string"

}
]
},
"saveToSentItems":"false"
}

with header of

"content-type":"application/x-www-form-urlencoded"

"Authorization" : "bearer<access_token>"

but I am getting status code 415 with unsupported media type.

**Comment by TaralRathod** [comment]
I have got the solution. in SDK, values were not assigning to the ContentBytes, ContentType and name to the in class of MSGraphAttachment. I have assigned values and now it is working properly.

**Comment by jamescro** [comment]
Thanks for this contribution, and I apologize for the delay in our response. Please let us know if you encounter other issues.
