### ISSUE TITLE
Unable to run pod install

### ISSUE THREAD

**Issue by HugoTW** [microsoftgraph/iOS-objectivec-connect-sample#8]
The following error occurred after running "pod install" 
[!] Unable to find a specification for `MSGraphSDK`

I'm using pod v 1.1.1 with Mac OS 10.12
Many thanks.

**Comment by DianeD** [comment]
Hi @HugoTW . Thanks for reporting this issue. Looking into it now.

**Comment by DianeD** [comment]
@HugoTW . I was able to run `pod install` using pod version 1.2.0 on OS 10.12. Would you be able to update CocoaPods and see if your issue still repros? If so, can you also run `pod list` and give the version of the installed MSGraphSDK?

**Comment by HugoTW** [comment]
Hello @DianeD . After updating to pod v1.2.0. , and running pod list, I did get following message : 
[!] An unexpected version directory `Common` was encountered for the `/Users/myUserName/.cocoapods/repos/microsoftgraph/MSGraphSDK` Pod in the `MSGraphSDK` repository.

Can you please have a look? Thanks!

**Comment by DianeD** [comment]
@HugoTW . Thanks for updating. 

Did you run `pod install` again? If so, did you get the same error that you first reported? 

If running `pod install` doesn't work, can you try `pod update`?

**Comment by HugoTW** [comment]
@DianeD. I just update the gem and fix all the issue. Thanks for the `update` command.
