### ISSUE TITLE
MSlogger file 

### ISSUE THREAD

**Issue by arjunnna** [microsoftgraph/iOS-objectivec-connect-sample#9]
Hi , 
in pods MSlogger file is conflicting with other pods . they are are also using same file name so I am getting error like files are duplicated . 

can you please change the file and update the code .

**Comment by JohnMAustin78** [comment]
Hi Arjunna,

I will update the logger file to a unique name.

John

**Comment by jasonjoh** [comment]
Closing this issue as we are archiving this repository. Please see https://github.com/microsoftgraph/msgraph-training-ios-objectivec for an Objective-C sample.
